// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kssitjzomloujsgtplqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtzc2l0anpvbWxvdWpzZ3RwbHFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODEzMjEsImV4cCI6MjA3MDc1NzMyMX0.z9z0gNJEahgJaNhTru5yK-MVrM4jbMToiwZNBoUjNSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});